### ISSUE TITLE
Touch transparent background

### ISSUE THREAD

**Issue by lostirc** [m1entus/MZFormSheetPresentationController#1]
Thanks for the great library. In the older MZFormSheetController you included support for touch transparent backgrounds using `formSheet.formSheetWindow.transparentTouchEnabled = YES`. Is this behavior supported in MZFormSheetPresentationController?

**Comment by m1entus** [comment]
There is no way to support it using new iOS8 modal presentation API. Transparent Touch was possible because MZFormSheetController is presented on separated UIWindow. MZFormSheetPresentationController is presented modally on UIDimmedView or something like this (by UIKit), not sure if it is possible to disable touching on this view.

**Comment by m1entus** [comment]
I have added support for transparent background :)

**Comment by lostirc** [comment]
Awesome work, thanks so much!
