### ISSUE TITLE
'MZFormSheetPresentationViewController' has no member 'shouldApplyBackgroundBlurEffect'

### ISSUE THREAD

**Issue by mirzadelic** [m1entus/MZFormSheetPresentationController#35]
Error:
```
Value of type 'MZFormSheetPresentationViewController' has no member 'shouldApplyBackgroundBlurEffect'
```

Code:
```
        let controller = self.storyboard!.instantiateViewControllerWithIdentifier("addArticleToGroup") as! AddArticleToGroupViewController
        controller.group = data
        let formSheetController = MZFormSheetPresentationViewController(contentViewController: controller)
        formSheetController.shouldApplyBackgroundBlurEffect = true // error here
        self.presentViewController(formSheetController, animated: true, completion: nil)
```

**Comment by m1entus** [comment]
Upgrade from 1.x

As a major version change, the API introduced in 2.0 is not backward compatible with 1.x integrations. Upgrading is straightforward.

Use MZFormSheetPresentationViewController instead of MZFormSheetPresentationController

MZFormSheetPresentationController now inherits from UIPresentationController and manage presentation of popup

-> MZFormSheetPresentationViewController have property presentationController which allows you customization presented content view

MZFormSheetPresentationController registerTransitionClass is now MZTransition registerTransitionClass

func entryFormSheetControllerTransition(formSheetController: MZFormSheetPresentationController, completionHandler: MZTransitionCompletionHandler) changed to func entryFormSheetControllerTransition(formSheetController: UIViewController, completionHandler: MZTransitionCompletionHandler) which formSheetController frame is equal to contentViewSize with view origin.
