### ISSUE TITLE
Clicking on the background to dismiss the formsheetpresentationcontroller sometimes doesn't dismiss but only un-blur the background

### ISSUE THREAD

**Issue by JosephZZ** [m1entus/MZFormSheetPresentationController#58]
After present a view controller, and generally after I click on some parts in this presented view, and then when I click on the background, this view doesn't disappear but only causes the background from blur to clear. I saw someone else also have this problem from the older version https://github.com/m1entus/MZFormSheetController/issues/191.

**Comment by m1entus** [comment]
Can you prepare simple demo for that? You can have some issues in your application like keepin strong reference or something else..

**Comment by JosephZZ** [comment]
Before clicking the background:
<img width="352" alt="screen shot 2016-02-10 at 4 13 04 pm" src="https://cloud.githubusercontent.com/assets/6688628/12995680/2695d33e-d0de-11e5-8d16-8bcf0e03e9c6.png">
After clicking the background:
<img width="330" alt="screen shot 2016-02-10 at 4 12 41 pm" src="https://cloud.githubusercontent.com/assets/6688628/12995689/3afa50de-d0de-11e5-9400-a0e40ad4f015.png">

The code is just simple code:
`let selectAlbumController = self.formSheetAlbumSelectionController() as! SelectAlbumTableFormSheetViewController
let formSheetController = MZFormSheetPresentationViewController(contentViewController: selectAlbumController)
//some more code for setting the transition effect
self.presentViewController(formSheetController, animated: true, completion: nil)`

To your strong reference point, my SelectAlbumTableFormSheetViewController has a delegate variable of my own protocol, and it has IBAction reference to it.  Don't know if this information would help.

**Comment by JosephZZ** [comment]
I guess it might have to do with table view delegate. This problem would only happen if I scroll the table view up and down pretty fast. And this view would not exist no matter if I click the background or select a cell (which would trigger dismissingview function).

**Comment by m1entus** [comment]
I need a sample because uou could keep strong reference to some of viewController thats why it is not dismissing

**Comment by JosephZZ** [comment]
yeah sure. just to clarify, when you say "sample" you mean a code project that can replicate this bug?

**Comment by m1entus** [comment]
Yes, Short example rhat can replicate this

**Comment by Nonepse** [comment]
I have been encountering the same issue for a few months now.
It's clearly not easy to reproduce, but I have been able to gather some info while testing my app:

- It happens on 2.1.3 and 2.3.0 (only versions tested)
- It indeed seems to be triggered easier when scrolling fast in the modal (may even be the only way to trigger it)
- A pan gesture won't trigger the issue (although I *seem* to remember it already happened, but really not sure)
- When the issue occurs, `willDismissContentViewControllerHandler` is called, `didDismissContentViewControllerHandler` is not. (`viewDidDisappear:` in `MZFormSheetPresentationViewController.m` is not called either)

Here is my code:

```objective-c
- (void)openProfile
{
    UIViewController *modalViewController = [[UIViewController alloc] init];

    UINavigationController *modalNavigationController = [[UINavigationController alloc]
                                                         initWithRootViewController:modalViewController];

    UIBarButtonItem *closeButton = [[UIBarButtonItem alloc]
                                    initWithBarButtonSystemItem:UIBarButtonSystemItemDone
                                    target:self
                                    action:@selector(closeModal)];

    modalViewController.navigationItem.leftBarButtonItem = closeButton;

    MZFormSheetPresentationViewController *formSheetController =
    [[MZFormSheetPresentationViewController alloc] initWithContentViewController:modalNavigationController];

    formSheetController.interactivePanGestureDissmisalDirection = MZFormSheetPanGestureDismissDirectionAll;
    formSheetController.contentViewControllerTransitionStyle = MZFormSheetPresentationTransitionStyleSlideFromBottom;
    formSheetController.presentationController.contentViewSize = ModalSize;

    [self.navigationController presentViewController:formSheetController animated:YES completion:nil];
}

- (void)closeModal
{
    [self.navigationController dismissViewControllerAnimated:YES completion:nil];
}
```

In my app, `modalViewController` class is a custom subclass of `UIViewController`. I won't put all my code here because I think it's irrelevant (and it would take pages and), but also because it's a closed-source project.
Do you think it's necessary to you?

Attempts to fix it which didn't change anything:
- Sending `dismissViewControllerAnimated:YES completion:nil` to the parent navigation controller, or to the modal view controller, or to the modal navigation controller, or to the `MZFormSheetPresentationViewController` object.
- In `MZFormSheetPresentationViewController.h`, calling `super` on first line of `viewWillDisappear` and `viewDidDisappear` overrides.

**Comment by m1entus** [comment]
If you prepare some short sample project where this exist, this will be for me very super fast to try to fix that, i am lazy man, without this it could take some time to make it by myself :dancer: So please craete sample project, and i will help you guyse

**Comment by Nonepse** [comment]
Will do.

**Comment by Nonepse** [comment]
Here you go: https://cloudup.com/c4clYcQzCcc
I tried to code the smallest project possible to reproduce issue.

In a simple project like that, the issue appears way less often.
And since the issue happens much more rarely on simulator than on device, I have been able to reproduce it on device only (iPhone 6 in my case).

I end up with the following state (you can see the background is not dimmed) :

![img_0028 copy](https://cloud.githubusercontent.com/assets/5849587/13635776/e318a104-e5f5-11e5-9540-f8e10fdc4705.PNG)
(sorry for the poneyland colors)

In that state, the `Done` button does nothing, and the only way to dismiss the modal is by using a pan gesture.

**Comment by m1entus** [comment]
The issue is because mixing interactive and normal animator, i need more time to fix the issue. Could you tell me how to reproduce your issue (what to do) because i probably i could found another issue.

**Comment by Nonepse** [comment]
To reproduce the issue you have to open the modal, scroll a few times in it, then hit the `Done` button.
It may happen once every 5 times, ad well as once every 60 times. As I said, it's hard to reproduce...

**Comment by m1entus** [comment]
Okay so it is the same issue, you need to in the same time click done button and try to pan to dismiss and will be reproducible, i will take care of it in some time

**Comment by Nonepse** [comment]
Ha, yeah you're right. If I press and hold the `Done` button and just after try to swipe down (while keeping, release, and then hit the `Done` button, it happens systematically.

**Comment by KevinJue** [comment]
this is actually not fixed. 
we should reopen it
