### ISSUE TITLE
frameConfigurationHandler problem with keyboard

### ISSUE THREAD

**Issue by Skornos** [m1entus/MZFormSheetPresentationController#61]
Hi,

I am using `frameConfigurationHandler` to align my presented view to the bottom of the screen like this:
```
        formSheetController.presentationController.frameConfigurationHandler = ^(UIView *presentedView, CGRect currentFrame) {
            return CGRectMake(currentFrame.origin.x, weakSelf.view.frame.size.height - currentFrame.size.height, currentFrame.size.width, currentFrame.size.height);
        };
```

At the same time this view aligned to the bottom contains 2 input TextFields so I am also setting `movementActionWhenKeyboardAppears`
```
formSheet.presentationController.movementActionWhenKeyboardAppears = MZFormSheetActionWhenKeyboardAppearsMoveToTopInset;
```

The problem is that when I tap the textField the keyboard covers the whole bottom view which doesn't slide up. I suppose it is a conflict between setting my custom frame and displaying keyboard. 
Or am I doing something wrong?

Thanks :)

**Comment by m1entus** [comment]
As you can see here: https://github.com/m1entus/MZFormSheetPresentationController/blob/master/MZFormSheetPresentationController/MZFormSheetPresentationController.m#L486 If you set frameConfigurationHandler then you are responsible for keyboard movement as well.

**Comment by Skornos** [comment]
Thanks for your quick response. Would it be possible to adjust the library to pass the property `keyboardVisible` to the `frameConfigurationHandler` along with the `self.presentedView` and `formSheetRect`?

I think it makes sense because these 3 properties are the ones which define how the frame should display and the `frameConfigurationHandler` is called when the keyboard appears. Otherwise I would need to register for keyboard notifications which seems redundant if you are doing this in your code already.

**Comment by m1entus** [comment]
Sure, that make sense, i also exposed isKeyboardVisible property in presentationController. Thanks.

**Comment by MarkPolivchuk** [comment]
I want to anchor the bottom of the form sheet to the top of the keyboard but don't know how to get the keyboard's frame (height specifically) without registering for notifications. Would it be possible to expose `screenFrameWhenKeyboardVisible` too?

**Comment by m1entus** [comment]
use `MZFormSheetActionWhenKeyboardAppearsAboveKeyboard` on presentationController

**Comment by MarkPolivchuk** [comment]
I'm using `.AlwaysAboveKeyboard` because my Form Sheet is full screen. 

Here are a few screenshots of what I mean:

Present VC in landscape, open keyboard in landscape:  (perfect!)
![image](https://cloud.githubusercontent.com/assets/11237023/17628137/2e713d78-6071-11e6-82dd-9fd1dc7317fa.png)

Present VC in landscape, open keyboard in portrait: (VC isn't moving up enough)
![image](https://cloud.githubusercontent.com/assets/11237023/17628150/3b669a46-6071-11e6-8dfa-18eeab7a15d8.png)

Present VC in portrait, open keyboard in landscape (VC is moving up too much)
![image](https://cloud.githubusercontent.com/assets/11237023/17628426/85a4e7ec-6072-11e6-98e0-958f8d58298a.png)

**Comment by nizzam** [comment]
What is the fixed for this ?
