### ISSUE TITLE
New release for Carthage header changes 

### ISSUE THREAD

**Issue by chazmo03** [m1entus/MZFormSheetPresentationController#92]
Can you publish a new release that includes all of the changes to the header files and such that make the Carthage installation work?

**Comment by m1entus** [comment]
Publish, where?

**Comment by chazmo03** [comment]
Here in Github. The last release is 2.4.0 from April 19th.

**Comment by KHellkvist** [comment]
@chazmo03 me and some other people( @eliburke ) has made some of the Carthage support.
Since @m1entus  doesn't use Carthage himself. It is indeed a bit problematic with this "half"-support.
But you could use:
`github "m1entus/MZFormSheetPresentationController" "master"`
in your cartfile to get all updates from master.
Or you could specify a commit if you feel that's safer!

**Comment by eliburke** [comment]
See #97 for another Carthage related fix. Hopefully Michał will merge it, but if he doesn't create a new release tag you will need to specify a commit in your carthage file like this:
github "eliburke/MZFormSheetPresentationController" "b34c93e"
(that's my repo, if the merge of #97 goes through then you should link against that)

**Comment by m1entus** [comment]
I released 2.4.1 and i think i can close it
